FLASK_APP=main.py
FLASK_ENV=development
CLOUD_SQL_USERNAME=logo-generator
CLOUD_SQL_PASSWORD=cl97cge239bf09m
CLOUD_SQL_DATABASE_NAME=logo_generator
CLOUD_SQL_CONNECTION_NAME=logo-generator-315910:europe-west3:logo-generator