FLASK_APP=main.py
FLASK_ENV=development
CLOUD_SQL_USERNAME=honza
CLOUD_SQL_PASSWORD=honza-logo-generator-99-00
CLOUD_SQL_DATABASE_NAME=logo_generator
CLOUD_SQL_CONNECTION_NAME=logo-generator-315910:europe-west3:logo-generator