# [START gae_python37_cloudsql_config]
runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /app/static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  CLOUD_SQL_USERNAME: logo-generator
  CLOUD_SQL_PASSWORD: cl97cge239bf09m
  CLOUD_SQL_DATABASE_NAME: logo_generator
  CLOUD_SQL_CONNECTION_NAME: logo-generator-315910:europe-west3:logo-generator
# [END gae_python37_cloudsql_config]